name: Publish

# Allow to run this workflow manually from the Actions tab
on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package to publish'
        type: string
        required: true
        default: 'mikel'
## Set permissions to the github token
## https://github.com/softprops/action-gh-release#permissions 
permissions:
  contents: write

jobs:
  publish:
    if: ${{ github.repository == 'jmjuanes/mikel' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'
      - name: Publish primary package
        run: npm publish
        if: ${{ inputs.package == 'mikel' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish secondary package
        run: cd packages/${{ inputs.package }} && npm publish
        if: ${{ inputs.package != 'mikel' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
