name: Release
on:
  push:
    tags: ['*']

## Set permissions to the github token
## https://github.com/softprops/action-gh-release#permissions 
permissions:
  contents: write

jobs:
  release:
    name: Release
    if: ${{ github.repository == 'jmjuanes/mikel' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
